[{{table.name}}]
natural_key = [{{ table.natural_key | map('autoquote') |join(', ') }}]
{%- if not table.primary_key %}
primary_key = ""
{%- endif %}
{%- if table.not_null %}
not_null = [{{ table.not_null | map('autoquote') |join(', ') }}]
{%- endif %}
[{{table.name}}.columns]
{% for col_name, col in table.columns.items() if not skip_col(col_name)-%}
{{col_name}} = "{{col.dtype}}"
{% endfor -%}
{% if table.foreign_keys -%}
[{{table.name}}.foreign_keys]
{% for col, ftable in table.foreign_keys.items() -%}
{{col}} = "{{ftable}}"
{% endfor %}
{% endif %}