SELECT DISTINCT
   rc.CONSTRAINT_NAME,
   tc.TABLE_NAME,
   kcu.COLUMN_NAME,
   ccu.TABLE_NAME AS foreign_table_name,
   ccu.COLUMN_NAME AS foreign_column_name
 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
 JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
   ON rc.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
 JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
   ON rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
 JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
   ON rc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
 WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
   AND tc.TABLE_SCHEMA = '{{pg_schema}}'
 ORDER BY
   rc.CONSTRAINT_NAME,
   tc.TABLE_NAME;
